# $PROJECT_ID resolves to the current project's ID
# ${_SERVICE} must be provided via --substitutions=_SERVICE=my-service-name argument.

# gcloud builds submit --substitutions _SERVICE=service-name

# See the link below for details on setting default values for substitutions
# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values

steps:
  
- id: docker-build-push-service
  waitFor: ['-']
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - | 
    docker build -t gcr.io/$PROJECT_ID/${_SERVICE} . && \
    docker push gcr.io/$PROJECT_ID/${_SERVICE}
- id: gcloud-run-deploy-backend-processor
  waitFor: ['docker-build-push-service']
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args: 
  - -c
  - | 
    gcloud run deploy ${_SERVICE} \
      --project $PROJECT_ID \
      --image gcr.io/$PROJECT_ID/${_SERVICE} \
      --timeout 15m \
      --region us-east4 \
      --platform managed \
      --min-instances 0 \
      --max-instances 5 \
      --allow-unauthenticated

substitutions:
  _SERVICE: dfcx-stte-example
