# A path to the file where the names are listed.
source_file: data/full_names.json
# The minimum degress of freedom - don't touch unless you need to tweak the model.
min_df: 1
# The number of neighbors to extract from k-Nearest Neighbors (affects the number of results)
n_neighbors: 5
out_file: ai-models/matcher
